/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas_oop;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class formComment extends javax.swing.JFrame {

    public formComment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNAMA = new javax.swing.JTextField();
        jTextFieldTEMPATTGLLAHIR = new javax.swing.JTextField();
        jTextFieldALAMAT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNIK = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jRadioButtonPEREMPUAN = new javax.swing.JRadioButton();
        jRadioButtonLAKILAKI = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldAGAMA = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldPEKERJAAN = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldBERLAKUHINGGA = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldKEWARGANEGARAAN = new javax.swing.JTextField();
        jButtonSIMPAN = new javax.swing.JButton();
        jButtonUBAH = new javax.swing.JButton();
        jButtonHAPUS = new javax.swing.JButton();
        jButtonCLEAR = new javax.swing.JButton();
        jTextFieldSEARCH = new javax.swing.JTextField();
        jButtonSEARCH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("PROGRAM APLIKASI REKAMAN KTP ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tempat/Tgl Lahir");

        jTextFieldNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNAMAActionPerformed(evt);
            }
        });

        jTextFieldTEMPATTGLLAHIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTEMPATTGLLAHIRActionPerformed(evt);
            }
        });

        jTextFieldALAMAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldALAMATActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jenis Kelamin");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("DESA PAPRINGAN");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("TAHUN 2023");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("NIK");

        jTextFieldNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNIKActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Alamat");

        jRadioButtonPEREMPUAN.setText("Perempuan");
        jRadioButtonPEREMPUAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPEREMPUANActionPerformed(evt);
            }
        });

        jRadioButtonLAKILAKI.setText("Laki-Laki");
        jRadioButtonLAKILAKI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLAKILAKIActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Agama");

        jTextFieldAGAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAGAMAActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Pekerjaan");

        jTextFieldPEKERJAAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPEKERJAANActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Kewarganegaraan");

        jTextFieldBERLAKUHINGGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBERLAKUHINGGAActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Berlaku Hingga");

        jTextFieldKEWARGANEGARAAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKEWARGANEGARAANActionPerformed(evt);
            }
        });

        jButtonSIMPAN.setBackground(java.awt.SystemColor.activeCaption);
        jButtonSIMPAN.setText("SIMPAN");
        jButtonSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSIMPANActionPerformed(evt);
            }
        });

        jButtonUBAH.setBackground(java.awt.SystemColor.activeCaption);
        jButtonUBAH.setText("UBAH");
        jButtonUBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUBAHActionPerformed(evt);
            }
        });

        jButtonHAPUS.setBackground(java.awt.SystemColor.activeCaption);
        jButtonHAPUS.setText("HAPUS");
        jButtonHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHAPUSActionPerformed(evt);
            }
        });

        jButtonCLEAR.setBackground(java.awt.SystemColor.activeCaption);
        jButtonCLEAR.setText("CLEAR");
        jButtonCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLEARActionPerformed(evt);
            }
        });

        jTextFieldSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSEARCHActionPerformed(evt);
            }
        });

        jButtonSEARCH.setBackground(java.awt.SystemColor.activeCaption);
        jButtonSEARCH.setText("SEARCH");
        jButtonSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSEARCHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldPEKERJAAN, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSIMPAN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonUBAH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonHAPUS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCLEAR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldKEWARGANEGARAAN)
                                .addGap(229, 229, 229))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldNIK, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jRadioButtonPEREMPUAN))
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButtonLAKILAKI)))
                                    .addGap(315, 315, 315))
                                .addComponent(jTextFieldTEMPATTGLLAHIR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(jLabel9))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldAGAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldBERLAKUHINGGA, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNIK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTEMPATTGLLAHIR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonPEREMPUAN)
                    .addComponent(jRadioButtonLAKILAKI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAGAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPEKERJAAN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBERLAKUHINGGA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldKEWARGANEGARAAN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSIMPAN)
                    .addComponent(jButtonUBAH)
                    .addComponent(jButtonHAPUS)
                    .addComponent(jButtonCLEAR)
                    .addComponent(jTextFieldSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSEARCH))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTEMPATTGLLAHIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTEMPATTGLLAHIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTEMPATTGLLAHIRActionPerformed

    private void jTextFieldALAMATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldALAMATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldALAMATActionPerformed

    private void jRadioButtonPEREMPUANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPEREMPUANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPEREMPUANActionPerformed

    private void jRadioButtonLAKILAKIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLAKILAKIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonLAKILAKIActionPerformed

    private void jTextFieldAGAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAGAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAGAMAActionPerformed

    private void jTextFieldPEKERJAANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPEKERJAANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPEKERJAANActionPerformed

    private void jTextFieldBERLAKUHINGGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBERLAKUHINGGAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBERLAKUHINGGAActionPerformed

    private void jTextFieldKEWARGANEGARAANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKEWARGANEGARAANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKEWARGANEGARAANActionPerformed

    private void jTextFieldSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSEARCHActionPerformed
        // TODO add your handling code here:
         jButtonSEARCHActionPerformed(evt);
    }//GEN-LAST:event_jTextFieldSEARCHActionPerformed

    private void jButtonSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSIMPANActionPerformed
        // TODO add your handling code here:
          // Ambil nilai-nilai dari input field
    String nama = jTextFieldNAMA.getText();
    String tempatTanggalLahir = jTextFieldTEMPATTGLLAHIR.getText();
    String alamat = jTextFieldALAMAT.getText();
    String agama = jTextFieldAGAMA.getText();
    String pekerjaan = jTextFieldPEKERJAAN.getText();
    String berlakuHingga = jTextFieldBERLAKUHINGGA.getText();
    String kewarganegaraan = jTextFieldKEWARGANEGARAAN.getText();
    String nik = jTextFieldNIK.getText(); // Ambil NIK dari input field

    // Tentukan jenis kelamin yang dipilih
    String jenisKelamin = "";
    if (jRadioButtonLAKILAKI.isSelected()) {
        jenisKelamin = "Laki-laki";
    } else if (jRadioButtonPEREMPUAN.isSelected()) {
        jenisKelamin = "Perempuan";
    }

    // Inisialisasi koneksi ke database
    String url = "jdbc:mysql://localhost/uas_oop"; 
    String user = "username_database"; 
    String password = "password_database"; 

    try {
        // Buat koneksi ke database
        Connection connection = DriverManager.getConnection(url, user, password);

        // Query untuk menyimpan data ke tabel yang sesuai dalam database
        String query = "INSERT INTO data_ktp (nama, tempat_tanggal_lahir, jenis_kelamin, alamat, agama, pekerjaan, berlaku_hingga, kewarganegaraan, nik) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

        // Buat prepared statement
        PreparedStatement statement = connection.prepareStatement(query);

        // Set parameter pada statement sesuai data yang akan disimpan
        statement.setString(1, nama);
        statement.setString(2, tempatTanggalLahir);
        statement.setString(3, jenisKelamin);
        statement.setString(4, alamat);
        statement.setString(5, agama);
        statement.setString(6, pekerjaan);
        statement.setString(7, berlakuHingga);
        statement.setString(8, kewarganegaraan);
        statement.setString(9, nik);

        // Jalankan perintah untuk menyimpan data
        statement.executeUpdate();

        // Tampilkan pesan keberhasilan kepada pengguna
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan ke database!");

        // Tutup koneksi dan statement
        statement.close();
        connection.close();

    } catch (SQLException e) {
        // Tangani kesalahan apabila terjadi kesalahan saat menyimpan data ke database
        JOptionPane.showMessageDialog(this, "Error saat menyimpan data ke database: " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonSIMPANActionPerformed

    private void jTextFieldNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNAMAActionPerformed

    private void jTextFieldNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNIKActionPerformed

    private void jButtonUBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUBAHActionPerformed
        // TODO add your handling code here:
    String nama = jTextFieldNAMA.getText();
    String tempatTanggalLahir = jTextFieldTEMPATTGLLAHIR.getText();
    String alamat = jTextFieldALAMAT.getText();
    String agama = jTextFieldAGAMA.getText();
    String pekerjaan = jTextFieldPEKERJAAN.getText();
    String berlakuHingga = jTextFieldBERLAKUHINGGA.getText();
    String kewarganegaraan = jTextFieldKEWARGANEGARAAN.getText();
    String nik = jTextFieldNIK.getText();

    // Tentukan jenis kelamin yang dipilih
    String jenisKelamin = "";
    if (jRadioButtonLAKILAKI.isSelected()) {
        jenisKelamin = "Laki-laki";
    } else if (jRadioButtonPEREMPUAN.isSelected()) {
        jenisKelamin = "Perempuan";
    }

    // Inisialisasi koneksi ke database
    String url = "jdbc:mysql://localhost/uas_oop"; 
    String user = "username_database"; 
    String password = "password_database"; 

    try {
        // Buat koneksi ke database
        Connection connection = DriverManager.getConnection(url, user, password);

        // Query untuk mengubah data di tabel yang sesuai dalam database
        String query = "UPDATE data_ktp SET nama=?, tempat_tanggal_lahir=?, jenis_kelamin=?, alamat=?, agama=?, pekerjaan=?, berlaku_hingga=?, kewarganegaraan=? WHERE nik=?";

        // Buat prepared statement
        PreparedStatement statement = connection.prepareStatement(query);

        // Set parameter pada statement sesuai data yang akan diubah
        statement.setString(1, nama);
        statement.setString(2, tempatTanggalLahir);
        statement.setString(3, jenisKelamin);
        statement.setString(4, alamat);
        statement.setString(5, agama);
        statement.setString(6, pekerjaan);
        statement.setString(7, berlakuHingga);
        statement.setString(8, kewarganegaraan);
        statement.setString(9, nik);

        // Jalankan perintah untuk mengubah data
        int rowsUpdated = statement.executeUpdate();

        if (rowsUpdated > 0) {
            // Tampilkan pesan keberhasilan kepada pengguna
            JOptionPane.showMessageDialog(this, "Data berhasil diubah di database!");
        } else {
            // Tampilkan pesan jika data tidak ditemukan
            JOptionPane.showMessageDialog(this, "Data dengan NIK tersebut tidak ditemukan!");
        }

        // Tutup koneksi dan statement
        statement.close();
        connection.close();

    } catch (SQLException e) {
        // Tangani kesalahan apabila terjadi kesalahan saat mengubah data di database
        JOptionPane.showMessageDialog(this, "Error saat mengubah data di database: " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonUBAHActionPerformed

    private void jButtonHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHAPUSActionPerformed
        // TODO add your handling code here:
     String nik = jTextFieldNIK.getText();

    // Inisialisasi koneksi ke database
    String url = "jdbc:mysql://localhost/uas_oop";
    String user = "username_database"; 
    String password = "password_database";

    try {
        // Buat koneksi ke database
        Connection connection = DriverManager.getConnection(url, user, password);

        // Query untuk menghapus data dari tabel yang sesuai dalam database
        String query = "DELETE FROM data_ktp WHERE nik=?";

        // Buat prepared statement
        PreparedStatement statement = connection.prepareStatement(query);

        // Set parameter pada statement sesuai NIK yang akan dihapus
        statement.setString(1, nik);

        // Jalankan perintah untuk menghapus data
        int rowsDeleted = statement.executeUpdate();

        if (rowsDeleted > 0) {
            // Tampilkan pesan keberhasilan kepada pengguna
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus dari database!");
        } else {
            // Tampilkan pesan jika data dengan NIK tersebut tidak ditemukan
            JOptionPane.showMessageDialog(this, "Data dengan NIK tersebut tidak ditemukan!");
        }

        // Tutup koneksi dan statement
        statement.close();
        connection.close();

    } catch (SQLException e) {
        // Tangani kesalahan apabila terjadi kesalahan saat menghapus data dari database
        JOptionPane.showMessageDialog(this, "Error saat menghapus data dari database: " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonHAPUSActionPerformed

    private void jButtonCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLEARActionPerformed
        // TODO add your handling code here:
    jTextFieldNAMA.setText("");
    jTextFieldTEMPATTGLLAHIR.setText("");
    jTextFieldALAMAT.setText("");
    jTextFieldAGAMA.setText("");
    jTextFieldPEKERJAAN.setText("");
    jTextFieldBERLAKUHINGGA.setText("");
    jTextFieldKEWARGANEGARAAN.setText("");
    jTextFieldNIK.setText("");
    
    // Unselect jenis kelamin
    jRadioButtonLAKILAKI.setSelected(false);
    jRadioButtonPEREMPUAN.setSelected(false);
    }//GEN-LAST:event_jButtonCLEARActionPerformed

    private void jButtonSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSEARCHActionPerformed
        // TODO add your handling code here:
        String searchName = jTextFieldSEARCH.getText();

    // Inisialisasi koneksi ke database
    String url = "jdbc:mysql://localhost/uas_oop"; // Ganti 'nama_database' dengan nama database Anda
    String user = "username_database"; // Ganti 'username_database' dengan username database Anda
    String password = "password_database"; // Ganti 'password_database' dengan password database Anda

    try {
        // Buat koneksi ke database
        Connection connection = DriverManager.getConnection(url, user, password);

        // Query untuk mencari data berdasarkan nama
        String query = "SELECT * FROM data_ktp WHERE nama LIKE ?";

        // Buat prepared statement
        PreparedStatement statement = connection.prepareStatement(query);

        // Set parameter pada statement sesuai kriteria pencarian nama
        statement.setString(1, "%" + searchName + "%");

        // Jalankan perintah untuk melakukan pencarian
        ResultSet resultSet = statement.executeQuery();

        // Cek apakah ada hasil yang ditemukan
        if (resultSet.next()) {
            // Jika data ditemukan, tampilkan data pada input field
            jTextFieldNAMA.setText(resultSet.getString("nama"));
            jTextFieldTEMPATTGLLAHIR.setText(resultSet.getString("tempat_tanggal_lahir"));
            jTextFieldALAMAT.setText(resultSet.getString("alamat"));
            jTextFieldAGAMA.setText(resultSet.getString("agama"));
            jTextFieldPEKERJAAN.setText(resultSet.getString("pekerjaan"));
            jTextFieldBERLAKUHINGGA.setText(resultSet.getString("berlaku_hingga"));
            jTextFieldKEWARGANEGARAAN.setText(resultSet.getString("kewarganegaraan"));
            jTextFieldNIK.setText(resultSet.getString("nik"));

            // Tentukan jenis kelamin berdasarkan nilai di database
            String jenisKelamin = resultSet.getString("jenis_kelamin");
            if ("Laki-laki".equals(jenisKelamin)) {
                jRadioButtonLAKILAKI.setSelected(true);
                jRadioButtonPEREMPUAN.setSelected(false);
            } else if ("Perempuan".equals(jenisKelamin)) {
                jRadioButtonLAKILAKI.setSelected(false);
                jRadioButtonPEREMPUAN.setSelected(true);
            }

        } else {
            // Jika data tidak ditemukan, kosongkan semua input field dan unselect jenis kelamin
            jTextFieldNAMA.setText("");
            jTextFieldTEMPATTGLLAHIR.setText("");
            jTextFieldALAMAT.setText("");
            jTextFieldAGAMA.setText("");
            jTextFieldPEKERJAAN.setText("");
            jTextFieldBERLAKUHINGGA.setText("");
            jTextFieldKEWARGANEGARAAN.setText("");
            jTextFieldNIK.setText("");

            jRadioButtonLAKILAKI.setSelected(false);
            jRadioButtonPEREMPUAN.setSelected(false);

            // Tampilkan pesan bahwa data dengan nama tersebut tidak ditemukan
            JOptionPane.showMessageDialog(this, "Data dengan nama tersebut tidak ditemukan!");
        }

        // Tutup koneksi, statement, dan resultSet
        resultSet.close();
        statement.close();
        connection.close();

    } catch (SQLException e) {
        // Tangani kesalahan apabila terjadi kesalahan saat melakukan pencarian data di database
        JOptionPane.showMessageDialog(this, "Error saat mencari data di database: " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonSEARCHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formComment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formComment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formComment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formComment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formComment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonCLEAR;
    private javax.swing.JButton jButtonHAPUS;
    private javax.swing.JButton jButtonSEARCH;
    private javax.swing.JButton jButtonSIMPAN;
    private javax.swing.JButton jButtonUBAH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonLAKILAKI;
    private javax.swing.JRadioButton jRadioButtonPEREMPUAN;
    private javax.swing.JTextField jTextFieldAGAMA;
    private javax.swing.JTextField jTextFieldALAMAT;
    private javax.swing.JTextField jTextFieldBERLAKUHINGGA;
    private javax.swing.JTextField jTextFieldKEWARGANEGARAAN;
    private javax.swing.JTextField jTextFieldNAMA;
    private javax.swing.JTextField jTextFieldNIK;
    private javax.swing.JTextField jTextFieldPEKERJAAN;
    private javax.swing.JTextField jTextFieldSEARCH;
    private javax.swing.JTextField jTextFieldTEMPATTGLLAHIR;
    // End of variables declaration//GEN-END:variables
}
